import { GoogleMap, Marker, useLoadScript } from "@react-google-maps/api";
import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

function initMap(){
	var map;
	var Path;
	map = new google.maps.Map(document.getElementById('map'),{
		zoom: 13,
		// Pusat: Kantor Camat Seririt
		center: {lat: -8.192452, lng: 114.938026}, 
		options: {
			fullscreenControl: false,
			zoomControl: false,
			keyboardShortcuts: false,
		},
	});
	map.data.addGeoJson(dataJson);

	Path = new google.maps.Polyline({
		geodesic: true,
		strokeColor: '#FF0000',
		strokeOpacity: 1.0,
		strokeWeight: 2
	});
	Path.setMap(map);
	var line = Path.getPath();
	var temp = new google.maps.LatLng({
		lat: -8.192452, 
		lng: 114.938026
	});
	line.push(temp);
	temp = new google.maps.LatLng({
		lat: -8.192828, 
		lng: 114.936633
	});
	line.push(temp);
}

export default function Aplikasi() {
  const {isLoaded} = useLoadScript({
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
  });
  if (!isLoaded) return <div>Maps loading...</div>
  return (
    <>
			<Head>
				<title>Lagasin - Aplikasi</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<style jsx global>{`
				.aplikasi{
					color: white;
					font-weight: 700;
				}
				.beranda{
					font-weight: 400;
					--tw-text-opacity: 1;
					color: rgb(207 250 254 / var(--tw-text-opacity));
				}
				.informasi{
					font-weight: 400;
					--tw-text-opacity: 1;
					color: rgb(207 250 254 / var(--tw-text-opacity));
				}
			`}</style>
			<Navbar/>
      <div className="container p-6 max-w-md mx-auto bg-cyan-100 sm:max-w-xl md:max-w-2xl lg:max-w-5xl min-h-screen">
        <h1 className="font-bold text-3xl mt-14">Lagasin</h1>
        <p className="my-3">Untuk menggunakan aplikasi Lagasin, silakan masukkan nomor dari titik yang sudah tersedia.</p>
        <div className="mb-3">
          <input
						type="number"
            name="num"
						className="rounded-md h-9 mr-2 pl-2 border-2 border-slate-300 focus:border-sky-300 focus:outline-none"
						placeholder="Masukkan nomor"
						required
						autoComplete="off"
					/>
					<button 
						onClick={initMap}
						className="rounded-md bg-sky-400 p-2 text-sm font-bold text-white hover:bg-sky-500 shadow-sm hover:shadow-md"
						id="submit"
					>
						Hitung
					</button>
				</div>
				<div className="bg-yellow-200 w-fit px-2 py-0.5 rounded-md mb-3">
					<details>
						<summary className="font-bold">
							Catatan:
						</summary>
							<p className="text-xs leading-6">
								Jika muncul pesan{" "}
								<kbd className="rounded-md bg-white py-0.5 px-1 font-bold text-black">
									This page can&apos;t load Google Maps correctly.
								</kbd>{" "}
								pada Google Maps, silakan klik tombol{" "}
								<kbd className="rounded-md bg-white py-0.5 px-1 font-bold text-black">OK</kbd>
							</p>
					</details>
				</div>
				<div id="map" className="w-ful min-h-screen shadow-md rounded-md">
				<GoogleMap
						zoom={13}
						center={{lat: -8.192452, lng: 114.938026}}
						options={{
							fullscreenControl: false,
							zoomControl: false,
							keyboardShortcuts: false,
						}}
						mapContainerClassName="w-full min-h-screen shadow-md rounded-md"
					>
						<Marker position={
								{
									// Kantor Camat
      						// (-8.192452, 114.938026)
									lat: -8.192452, lng: 114.938026,
								}
							}/>
						<Marker position={
								{
									// Puskesmas Seririt 1
      						// (-8.192828, 114.936633)
									lat: -8.192828, lng: 114.936633,
								}
							}/>
						<Marker position={
								{
									// Puskesmas Seririt 2
      						// (-8.203176, 114.886372)
									lat: -8.203176, lng: 114.886372,
								}
							}/>
						<Marker position={
								{
									// Puskesmas Seririt 3
      						// (-8.223675, 114.942618)
									lat: -8.223675, lng: 114.942618,
								}
							}/>
						<Marker position={
								{
									// Rumah Sakit Pratama - Tangguwisia
      						// (-8.191781, 114.950825)
									lat: -8.191781, lng: 114.950825,
								}
							}/>
						<Marker position={
								{
									// Rumah Sakit Santi Graha - Sulanyah
      						// (-8.195790, 114.943202)
									lat: -8.195790, lng: 114.943202,
								}
							}/>
					</GoogleMap>
				</div>				
			</div>
			<Footer/>
    </>
  );
}