import { useMemo } from "react";
import { GoogleMap, InfoWindowF, Marker, MarkerF, useLoadScript } from "@react-google-maps/api";
import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
export default function Aplikasi() {
  const {isLoaded} = useLoadScript({
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
  });
  if (!isLoaded) return <div>Maps loading...</div>
  return (
    <>
			<Head>
					<title>Lagasin - Aplikasi</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
			</Head>
			<style jsx global>{`
				.aplikasi{
					color: white;
					font-weight: 700;
				}
				.beranda{
					font-weight: 400;
					--tw-text-opacity: 1;
					color: rgb(207 250 254 / var(--tw-text-opacity));
				}
				.informasi{
					font-weight: 400;
					--tw-text-opacity: 1;
					color: rgb(207 250 254 / var(--tw-text-opacity));
				}
			`}</style>
			<Navbar/>
      <div className="container p-6 max-w-md mx-auto bg-cyan-100 sm:max-w-xl md:max-w-2xl lg:max-w-5xl min-h-screen">
        <h1 className="font-bold text-3xl mt-14">Lagasin</h1>
        <p className="my-3">Untuk menggunakan aplikasi Lagasin, silakan masukkan nomor dari titik yang sudah tersedia.</p>
        <form action="" className="mb-3">
          <input
						type="number"
            name="num"
						className="rounded-md h-9 mr-2 pl-2 border-2 border-slate-300 focus:border-sky-300 focus:outline-none"
						placeholder="Masukkan nomor"
						required
					/>
					<button className="rounded-md bg-sky-400 p-2 text-sm font-bold text-white hover:bg-sky-500 shadow-sm hover:shadow-md">
							Hitung
					</button>
				</form>
				<div className="bg-yellow-200 w-fit px-2 py-0.5 rounded-md mb-3">
					<details>
						<summary className="font-bold">
							Catatan:
						</summary>
							<p className="text-xs leading-6">
								Jika muncul pesan{" "}
								<kbd className="rounded-md bg-white py-0.5 px-1 font-bold text-black">
									This page can&apos;t load Google Maps correctly.
								</kbd>{" "}
								pada Google Maps, silakan klik tombol{" "}
								<kbd className="rounded-md bg-white py-0.5 px-1 font-bold text-black">OK</kbd>
							</p>
					</details>
				</div>
				<Map/>
			</div>
			<Footer/>
    </>
  );
}

function Map() {
  const center = useMemo(() => ({lat: -8.192919, lng: 114.936617}), []);
  return(
    <GoogleMap
			zoom={18}
			center={center}
			options={
				{
					fullscreenControl: false,
					zoomControl: false,
					keyboardShortcuts: false,
				}
			}
			mapContainerClassName="min-h-screen w-full rounded-md">
				<Marker position={center}/>
        <InfoWindowF position={center}>
          <p>Lokasi awal</p>
        </InfoWindowF>
    </GoogleMap>
  );
}