import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
export default function Index() {
  return (
    <>
      <Head>
        <title>Lagasin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icon.ico" />
      </Head>
      <style jsx global>{`
        .beranda {
          color: white;
          font-weight: 700;
        }
        .aplikasi {
          font-weight: 400;
          --tw-text-opacity: 1;
          color: rgb(207 250 254 / var(--tw-text-opacity));
        }
        .informasi {
          font-weight: 400;
          --tw-text-opacity: 1;
          color: rgb(207 250 254 / var(--tw-text-opacity));
        }
      `}</style>
      <Navbar />
      <div className="bg-sky-50 mx-auto lg:px-16 xl:px-32 lg:max-w-7xl">
        {/* hero section */}
        <div className="min-h-screen pt-16 px-8">
          <div className="flex flex-col items-center lg:flex-row lg:justify-center lg:pt-28">
            <div
              data-aos="fade-up"
              className="mt-1 lg:flex lg:justify-center lg:item-center mb-5 lg:order-2 lg:mb-0 lg:w-1/2"
            >
              <Image
                src="/images/doctor.svg"
                height={280}
                width={280}
                alt="Logo Lagasin"
              />
              <div className="absolute -z-10 -top-2 lg:-top-16">
                <Image
                  src="/images/blob1.svg"
                  height={450}
                  width={450}
                  alt="Blob"
                />
              </div>
            </div>
            <div
              data-aos="fade-up"
              className="flex flex-col items-center justify-center text-center lg:order-1 lg:w-1/2 lg:text-left lg:items-start"
            >
              <h1 className="text-black font-extrabold mb-3 text-xl md:text-2xl xl:text-3xl 2xl:text-4xl">
                Cari <span className="font-extrabold text-sky-500">Vaksin</span>{" "}
                Jadi Mudah dengan{" "}
                <span className="font-extrabold text-sky-500">Lagasin</span>
              </h1>
              <p className="mb-5">
                Dapatkan vaksin di tempat vaksinasi terdekat dengan informasi yang
                cepat dan akurat.
              </p>
              <a href="#lagasin">
                <button className="rounded-md bg-sky-400 text-white font-bold shadow-xl hover:bg-sky-500 p-3">
                  Selengkapnya
                </button>
              </a>
            </div>
          </div>
        </div>
        {/* end of hero section */}
        {/* what is */}
        <div className="pt-24 min-h-screen px-8" id="lagasin">
          <div
            data-aos="fade-up"
            className="flex items-center justify-center text-black font-extrabold mb-3 text-xl md:text-2xl xl:text-3xl 2xl:text-4xl"
          >
            <h3>
              Apa itu <span className="text-pink-500">Lagasin?</span>
            </h3>
          </div>
          <div
            data-aos="fade-up"
            className="flex flex-col items-center justify-center p-9 md:flex-row"
          >
            <div className="flex items-center justify-center text-center mb-4 md:w-1/2 md:items-center md:justify-center md:text-center">
              <div className="absolute">
                <Image
                  src="/images/blob2.svg"
                  height={380}
                  width={400}
                  alt="People asking"
                />
              </div>
              <Image
                src="/images/peopleasking.svg"
                height={280}
                width={280}
                alt="People asking"
              />
            </div>
            <div className="md:w-1/2 text-center lg:text-justify mt-3 lg:mt-0">
              Lagasin adalah aplikasi pencarian tempat vaksinasi. 
              Mungkin Anda pernah ingin mendapatkan vaksin, tapi tempat yang Anda datangi tidak melaksanakan vaksinasi. 
              Oleh karena itu, Lagasin hadir untuk memberikan pencarian tempat vaksinasi terdekat bagi Anda, 
              khususnya di wilayah Kecamatan Seririt, Kabupaten Buleleng, Bali.
            </div>
          </div>
          <div className="flex justify-center mb-20 -mt-3">
            <Link href={"/informasi"}>
              <a>
                <button className="text-white p-3 rounded-md font-bold bg-pink-400 hover:bg-pink-500 shadow-md hover:shadow-lg">
                  Baca Selengkapnya
                </button>
              </a>
            </Link>
          </div>
        </div>
        {/* end of what is */}
        {/* why lagasin */}
        <div className="mt-40 min-h-screen px-8">
          <div
            data-aos="fade-up"
            className="flex items-center justify-center text-black font-extrabold text-xl md:text-2xl xl:text-3xl 2xl:text-4xl mb-16"
          >
            <h3>
              Mengapa harus <span className="text-sky-500">Lagasin?</span>
            </h3>
          </div>
          <div className="flex flex-col lg:flex-row lg:gap-x-10">
            <div
              data-aos="fade-up"
              className="bg-white p-3 flex flex-col text-center mb-3 shadow-md hover:shadow-lg rounded-lg"
            >
              <Image
                src="/images/development.svg"
                height={80}
                width={80}
                alt="Open Source"
              />
              <h3 className="font-bold text-md mt-3">Open Source</h3>
              <p>
                Lagasin adalah aplikasi open source, sehingga kode dari program
                dapat dilihat langsung.
              </p>
            </div>
            <div
              data-aos="fade-up"
              className="bg-white p-3 flex flex-col text-center mb-3 shadow-md hover:shadow-lg rounded-lg"
            >
              <Image
                src="/images/math.svg"
                height={80}
                width={80}
                alt="Open Source"
              />
              <h3 className="font-bold text-md mt-3">FW Algorithm</h3>
              <p>
                Lagasin menggunakan algoritma Floyd-Warshall yang mampu mencari
                tempat vaksinasi terdekat.
              </p>
            </div>
            <div
              data-aos="fade-up"
              className="bg-white p-3 flex flex-col text-center mb-3 shadow-md hover:shadow-lg rounded-lg"
            >
              <Image
                src="/images/map.svg"
                height={80}
                width={80}
                alt="Open Source"
              />
              <h3 className="font-bold text-md mt-3">Google Maps</h3>
              <p>
                Lagasin dibuat dengan bantuan API dari Google Maps, sehingga
                data akurat.
              </p>
            </div>
          </div>
        </div>
        {/* end of why lagasin */}
        {/* try now */}
        <div className="pt-20 lg:pt-0 h-96 pb-96 px-8">
          <div
            data-aos="fade-up"
            className="flex items-center justify-center text-black font-extrabold mb-4 text-xl md:text-2xl xl:text-3xl 2xl:text-4xl"
          >
            <h3>
              Coba <span className="text-sky-500">Lagasin </span> Sekarang!
            </h3>
          </div>
          <div className="flex flex-col items-center text-center">
            <div data-aos="fade-up" className="mb-4">
              Tertarik mencoba Lagasin? Ayo coba Lagasin untuk mencari tempat vaksinasi
              terdekat! Coba sekarang gratis!
            </div>
          </div>
          <div data-aos="fade-up" className="flex items-center justify-center">
            <Link href="/aplikasi">
              <button className="font-bold text-white bg-sky-400 p-3 rounded-lg shadow-md hover:shadow-lg hover:bg-sky-500">
                <a>Coba Sekarang</a>
              </button>
            </Link>
          </div>
        </div>
        {/* end of try now */}
      </div>
      <Footer />
    </>
  );
}
