import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
export default function Informasi() {
	return (
		<>
			<Head>
				<title>Lagasin - Informasi</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<style jsx global>{`
				.informasi{
					color: white;
					font-weight: 700;
				}
				.beranda{
					font-weight: 400;
					--tw-text-opacity: 1;
					color: rgb(207 250 254 / var(--tw-text-opacity));
				}
				.aplikasi{
					font-weight: 400;
					--tw-text-opacity: 1;
					color: rgb(207 250 254 / var(--tw-text-opacity));
				}
			`}</style>
			<Navbar/>
				<div className="container p-6 max-w-md mx-auto bg-cyan-100 sm:max-w-xl md:max-w-2xl lg:max-w-5xl min-h-screen">
					<h1 className="font-bold text-3xl">Informasi</h1>
					<p>Ini adalah tampilan informasi.</p>
				</div>
			<Footer/>
		</>
	);
}
